In [1]:
from LCS import LCSFinder
import numpy as np

In [2]:
# Define two sequences
s1 = np.array([0, 1, 1, 1, 1, 0, 0, 0])
s2 = np.array([0, 1, 1, 0, 0, 1, 0, 0])

In [3]:
# Create an instance of the LCSFinder class
lcs_finder = LCSFinder(s1, s2)

In [4]:
lcs_finder.GetSA() == [8, 16, 7, 15, 6, 5, 12, 13, 9, 0, 14, 4, 11, 3, 10, 2, 1]
# original code SA
# (8, 16, 7, 15, 6, 5, 12, 13, 9, 0, 14, 4, 11, 3, 10, 2, 1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

In [5]:
lcs_finder.GetS()

array([1, 2, 2, 2, 2, 1, 1, 1, 0, 1, 2, 2, 1, 1, 2, 1, 1])

In [6]:
lcs_finder.ComputeAllLCSs(np.array([(x,x+1) for x in range(len(s2))])) == [1, 1, 2, 3, 3, 2, 2, 1]

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [7]:
%timeit lcs_finder.ComputeAllLCSs([(x,x+1) for x in range(len(s2))])

# output from Max's code
# (1, 0, 0, 3, 3, 2, 1, 1)

51.4 µs ± 231 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [8]:
%%timeit
# Define two sequences
s1 = np.array([0, 1, 1, 1, 1, 0, 0, 0])
s2 = np.array([0, 1, 1, 0, 0, 1, 0, 0])
# Create an instance of the LCSFinder class
lcs_finder = LCSFinder(s1, s2)
lcs_finder.GetSA()
# original code SA
# (8, 7, 6, 1, 13, 2, 16, 5, 0, 12, 15, 4, 11, 14, 3, 10, 9)
lcs_finder.GetS() 
lcs_finder.ComputeAllLCSs([(x,x+1) for x in range(len(s2))])


116 µs ± 660 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


# From C++ code - to beat 19.7 µs ± 300 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [2]:
from LCS_Cython import *

# test without typing

In [4]:
%%timeit
# Define two sequences
s1 = np.array([0, 1, 1, 1, 1, 0, 0, 0])
s2 = np.array([0, 1, 1, 0, 0, 1, 0, 0])
# Create an instance of the LCSFinder class
lcs_finder = LCSFinder(s1, s2)
lcs_finder.GetSA()
# original code SA
# (8, 7, 6, 1, 13, 2, 16, 5, 0, 12, 15, 4, 11, 14, 3, 10, 9)
lcs_finder.GetS() 
lcs_finder.ComputeAllLCSs([(x,x+1) for x in range(len(s2))])


70.3 µs ± 2.41 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


# now with typing

In [7]:
from LCS_Cython import *

In [8]:
%%timeit
# Define two sequences
s1 = [0, 1, 1, 1, 1, 0, 0, 0]
s2 = [0, 1, 1, 0, 0, 1, 0, 0]
# Create an instance of the LCSFinder class
lcs_finder = LCSFinder(s1, s2)
lcs_finder.GetSA()
# original code SA
# (8, 7, 6, 1, 13, 2, 16, 5, 0, 12, 15, 4, 11, 14, 3, 10, 9)
lcs_finder.GetS() 
lcs_finder.ComputeAllLCSs([(x,x+1) for x in range(len(s2))])


34.9 µs ± 247 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


# List only

In [1]:
import LCS_Cython_LIST as lcs_list

In [2]:
%%timeit
# Define two sequences
s1 = [0, 1, 1, 1, 1, 0, 0, 0]
s2 = [0, 1, 1, 0, 0, 1, 0, 0]
# Create an instance of the LCSFinder class
lcs_finder = lcs_list.LCSFinder(s1, s2)
lcs_finder.GetSA()
# original code SA
# (8, 7, 6, 1, 13, 2, 16, 5, 0, 12, 15, 4, 11, 14, 3, 10, 9)
lcs_finder.GetS() 
lcs_finder.ComputeAllLCSs([(x,x+1) for x in range(len(s2))])


33.9 µs ± 213 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


# add typing to all lists

In [1]:
import LCS_Cython_LIST_typed as lcs_list_typed

In [2]:
# Define two sequences
s1 = [0, 1, 1, 1, 1, 0, 0, 0]
s2 = [0, 1, 1, 0, 0, 1, 0, 0]
# Create an instance of the LCSFinder class
lcs_finder = lcs_list_typed.LCSFinder(s1, s2)
lcs_finder.GetSA()
# original code SA
# (8, 7, 6, 1, 13, 2, 16, 5, 0, 12, 15, 4, 11, 14, 3, 10, 9)
lcs_finder.GetS() 
lcs_finder.ComputeAllLCSs([(x,x+1) for x in range(len(s2))])

[1, 1, 2, 3, 3, 2, 2, 1]

In [3]:
import numpy as np

In [4]:
%%timeit
# Define two sequences
s1 = list(np.random.randint(0,5,1000))
s2 = list(np.random.randint(0,5,1000))
# Create an instance of the LCSFinder class
lcs_finder = lcs_list_typed.LCSFinder(s1, s2)
lcs_finder.GetSA()
# original code SA
# (8, 7, 6, 1, 13, 2, 16, 5, 0, 12, 15, 4, 11, 14, 3, 10, 9)
lcs_finder.GetS() 
lcs_finder.ComputeAllLCSs([(x,x+1) for x in range(len(s2))])


18 ms ± 258 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# Debugging

In [9]:
from LCS import LCSFinder
import numpy as np

In [10]:
s1 = np.array([1, 1, 3, 0, 4, 1, 4, 4, 2, 1])
s2 = np.array([0, 1, 0, 1, 3, 2, 1, 4, 0, 0])

In [11]:
lcs_finder = LCSFinder(s2, s1)
[x+1 for x in lcs_finder.ComputeAllLCSs([(x,x+1) for x in range(len(s2))])]

11 0 0
12 1 1
13 2 0
14 3 0
15 4 0
16 5 0
17 6 0
18 7 1
19 8 0
20 9 0


[1, 2, 1, 1, 1, 1, 1, 2, 1, 1]

In [9]:
[x+1 for x in [0, 1, 0, 1, 0, 1, 0, 1, 2, 1]]

[1, 2, 1, 2, 1, 2, 1, 2, 3, 2]

In [6]:

lcs_finder.FindLCP(13,9)

False False False 4 6
True True False 4 6
True True False 4 6
True True False 3 5
True True False 1 2


0

In [ ]:
01001001012010

In [ ]:
array([1, 2, 1, 1, 2, 1, 3, 2, 2, 2])

In [4]:
lcs_finder = LCSFinder(s1, s2)
lcs_finder.GetSA()
lcs_finder.GetS() 
lcs_finder.ComputeAllLCSs([(x,x+1) for x in range(len(s2))])

11 0 0
12 1 1
13 2 0
14 3 0
15 4 0
16 5 0
17 6 0
18 7 1
19 8 0
20 9 0


[0, 1, 0, 0, 0, 0, 0, 1, 0, 0]

In [ ]:
         2 2 4 1 5 2 5 5 3 2 0 1 2 1 2 4 3 2 5 1 1
Rank is: 2 2 4 1 5 2 5 5 3 2 0 1 2 1 2 4 3 2 5 1 1 

p is: 1
         2 2 4 1 5 2 5 5 3 2 0 1 2 1 2 4 3 2 5 1 1
Rank is: 2 2 4 1 5 2 5 5 3 2 0 1 2 1 2 4 3 2 5 1 1 
                0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
Sorted aray is: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 
                     10 20 19 11 13 3 9 12 0 1 14 5 17 8 16 2 15 18 4 7 6
Post Sorted aray is: 10 20 19 11 13 3 9 12 0 1 14 5 17 8 16 2 15 18 4 7 6 

p is: 2
         7 8 11 4 14 9 16 15 10 5 0 3 6 3 8 12 10 9 13 2 1
Rank is: 7 8 11 4 14 9 16 15 10 5 0 3 6 3 8 12 10 9 13 2 1 
                10 20 19 11 13 3 9 12 0 1 14 5 17 8 16 2 15 18 4 7 6
Sorted aray is: 10 20 19 11 13 3 9 12 0 1 14 5 17 8 16 2 15 18 4 7 6 
                     10 20 19 11 13 3 9 12 0 1 14 17 5 8 16 2 15 18 4 7 6
Post Sorted aray is: 10 20 19 11 13 3 9 12 0 1 14 17 5 8 16 2 15 18 4 7 6 

p is: 4
         8 9 15 5 18 12 20 19 13 6 0 3 7 4 10 16 14 11 17 2 1
Rank is: 8 9 15 5 18 12 20 19 13 6 0 3 7 4 10 16 14 11 17 2 1 
                10 20 19 11 13 3 9 12 0 1 14 17 5 8 16 2 15 18 4 7 6
Sorted aray is: 10 20 19 11 13 3 9 12 0 1 14 17 5 8 16 2 15 18 4 7 6 
                     10 20 19 11 13 3 9 12 0 1 14 17 5 8 16 2 15 18 4 7 6
Post Sorted aray is: 10 20 19 11 13 3 9 12 0 1 14 17 5 8 16 2 15 18 4 7 6 

p is: 8
         8 9 15 5 18 12 20 19 13 6 0 3 7 4 10 16 14 11 17 2 1
Rank is: 8 9 15 5 18 12 20 19 13 6 0 3 7 4 10 16 14 11 17 2 1 
                10 20 19 11 13 3 9 12 0 1 14 17 5 8 16 2 15 18 4 7 6
Sorted aray is: 10 20 19 11 13 3 9 12 0 1 14 17 5 8 16 2 15 18 4 7 6 
                     10 20 19 11 13 3 9 12 0 1 14 17 5 8 16 2 15 18 4 7 6
Post Sorted aray is: 10 20 19 11 13 3 9 12 0 1 14 17 5 8 16 2 15 18 4 7 6 

p is: 16
         8 9 15 5 18 12 20 19 13 6 0 3 7 4 10 16 14 11 17 2 1
Rank is: 8 9 15 5 18 12 20 19 13 6 0 3 7 4 10 16 14 11 17 2 1 
                10 20 19 11 13 3 9 12 0 1 14 17 5 8 16 2 15 18 4 7 6
Sorted aray is: 10 20 19 11 13 3 9 12 0 1 14 17 5 8 16 2 15 18 4 7 6 
                     10 20 19 11 13 3 9 12 0 1 14 17 5 8 16 2 15 18 4 7 6
Post Sorted aray is: 10 20 19 11 13 3 9 12 0 1 14 17 5 8 16 2 15 18 4 7 6 

Final suffix aray is: 10 20 19 11 13 3 9 12 0 1 14 17 5 8 16 2 15 18 4 7 6 
                     (10 20 19 11 13 3 9 12 0 1 14 17 5 8 16 2 15 18 4 7 6)